name: azure deploy CI

on: 
  push

# Packages and deploys backend code to Azure
# Only runs when there is a push to the master branch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
           pushd Code/Backend/waitless-functions
           mvn clean package
           mvn azure-functions:package
           popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: waitless-functions-2
        package: ./Code/Backend/waitless-functions//target/azure-functions/waitless-functions-2
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

