name: mvn test CI

on: [push]

jobs:
  build:

# Mavan Ci that runs all backend test

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build the Docker image
          run: |
                pushd Code/Backend/waitless-functions
                docker build .
                popd
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build with Maven
          run: |
               pushd Code/Backend/waitless-functions
               mvn test
      
